Making the density state evolution


In [157]:
import numpy as np
import matplotlib.pyplot as plt
size = 8
gamma = np.diag([0.0]*size,k = 0)
for i in range(int(size/4)):
    gamma[i][i] = 1.0
print(gamma)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Fourier Transformed position matrix

In [158]:
#Fourier trnasform matrix
def array_element(x,y,energmatx):
    xy = 0.0
    for i in range(size):
        for j in range(size):
            xy += np.exp(1j*((i)*(x) - (j)*(y)))*(energmatx[i][j])
    return xy/size

position_matrix = np.fromfunction(lambda i, j: array_element(i,j,gamma), (size, size), dtype=int)
print(abs(position_matrix))


[[0.25       0.21939564 0.13507558 0.0176843  0.10403671 0.2002859
  0.24749812 0.23411417]
 [0.21939564 0.25       0.21939564 0.13507558 0.0176843  0.10403671
  0.2002859  0.24749812]
 [0.13507558 0.21939564 0.25       0.21939564 0.13507558 0.0176843
  0.10403671 0.2002859 ]
 [0.0176843  0.13507558 0.21939564 0.25       0.21939564 0.13507558
  0.0176843  0.10403671]
 [0.10403671 0.0176843  0.13507558 0.21939564 0.25       0.21939564
  0.13507558 0.0176843 ]
 [0.2002859  0.10403671 0.0176843  0.13507558 0.21939564 0.25
  0.21939564 0.13507558]
 [0.24749812 0.2002859  0.10403671 0.0176843  0.13507558 0.21939564
  0.25       0.21939564]
 [0.23411417 0.24749812 0.2002859  0.10403671 0.0176843  0.13507558
  0.21939564 0.25      ]]


In [159]:
J = 1.0
def arrayevol(i,j,correlation):
    return (-2*1j*(np.cos(i)-np.cos(j))*correlation[i][j]) + ((np.sum(correlation))/(size**2)) - ((correlation[i,:].sum() + correlation[:,j].sum())/(2*size))
print(arrayevol(2,0,gamma))
def evol(correlation):
    newgamma = np.zeros((size,size),dtype = complex)
    for i in range(size):
        for j in range(size):
            newgamma[i][j] = arrayevol(i,j,gamma)
    return newgamma
print(evol(gamma))
for time in range(50):
    gammanew = np.copy(gamma)
    gamma = gammanew + evol(gamma)
    print(np.diag(abs(np.fromfunction(lambda i, j: array_element(i,j,gamma), (size, size), dtype=int)),k = 0))
#for time in range(120):
#    gammanew = np.copy(gamma)
#    for i in range(np.shape(gamma)[0]):
#            for j in range(np.shape(gamma)[1]):
#                gamma[i][j] = (evol(gammanew,i,j)) + gammanew[i][j]
#    position_matrix = np.fromfunction(lambda i, j: array_element(i,j,gamma), (size, size), dtype=int)
#    print(position_matrix.real)


(-0.03125+0j)
[[-0.09375+0.j -0.09375+0.j -0.03125+0.j -0.03125+0.j -0.03125+0.j
  -0.03125+0.j -0.03125+0.j -0.03125+0.j]
 [-0.09375+0.j -0.09375+0.j -0.03125+0.j -0.03125+0.j -0.03125+0.j
  -0.03125+0.j -0.03125+0.j -0.03125+0.j]
 [-0.03125+0.j -0.03125+0.j  0.03125+0.j  0.03125+0.j  0.03125+0.j
   0.03125+0.j  0.03125+0.j  0.03125+0.j]
 [-0.03125+0.j -0.03125+0.j  0.03125+0.j  0.03125+0.j  0.03125+0.j
   0.03125+0.j  0.03125+0.j  0.03125+0.j]
 [-0.03125+0.j -0.03125+0.j  0.03125+0.j  0.03125+0.j  0.03125+0.j
   0.03125+0.j  0.03125+0.j  0.03125+0.j]
 [-0.03125+0.j -0.03125+0.j  0.03125+0.j  0.03125+0.j  0.03125+0.j
   0.03125+0.j  0.03125+0.j  0.03125+0.j]
 [-0.03125+0.j -0.03125+0.j  0.03125+0.j  0.03125+0.j  0.03125+0.j
   0.03125+0.j  0.03125+0.j  0.03125+0.j]
 [-0.03125+0.j -0.03125+0.j  0.03125+0.j  0.03125+0.j  0.03125+0.j
   0.03125+0.j  0.03125+0.j  0.03125+0.j]]
[0.25       0.21687587 0.23633877 0.25004689 0.246917   0.2300767
 0.2797645  0.26470873]
[0.25       0.27039232 